server {
    listen 80;
    server_name localhost;

    # ssl_certificate /etc/nginx/certs/local-gateway.crt;
    # ssl_certificate_key /etc/nginx/certs/local-gateway.key;

    location /api/auth/ {
        proxy_pass http://booking-auth-service:8080/;
    }
}